# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - task gen
  generate-protobuf:
    aliases:
      - gen
    desc: "command to generate new auth gRPC server and client"
    cmds:
      - protoc -I proto ./proto/*.proto --go_out=./gen/go --go_opt=paths=source_relative --go-grpc_out=./gen/go --go-grpc_opt=paths=source_relative